---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports/finalizers
  verbs:
  - update
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports/status
  verbs:
  - get
  - patch
  - update
