# permissions for end users to view weatherreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weatherreport-viewer-role
rules:
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports/status
  verbs:
  - get
