# permissions for end users to edit weatherreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: weatherreport-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weather-operator
    app.kubernetes.io/part-of: weather-operator
    app.kubernetes.io/managed-by: kustomize
  name: weatherreport-editor-role
rules:
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports/status
  verbs:
  - get
