# permissions for end users to edit weatherreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weatherreport-editor-role
rules:
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - weather.mrwinston.github.io
  resources:
  - weatherreports/status
  verbs:
  - get
