apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: weather-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WeatherReport is the Schema for the weatherreports API
      displayName: Weather Report
      kind: WeatherReport
      name: weatherreports.weather.mrwinston.github.io
      version: v1alpha1
  description: Get weather information right in your cluster
  displayName: weather-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - weather
  - utility
  links:
  - name: Weather Operator
    url: https://weather-operator.domain
  maturity: alpha
  provider:
    name: mrWinston
  version: 0.0.0
