package weather

const (
	WEATHER_VAR_DAILY_WEATHERCODE                   = "weathercode"
	WEATHER_VAR_DAILY_TEMPERATURE_2M_MAX            = "temperature_2m_max"
	WEATHER_VAR_DAILY_TEMPERATURE_2M_MIN            = "temperature_2m_min"
	WEATHER_VAR_DAILY_APPARENT_TEMPERATURE_MAX      = "apparent_temperature_max"
	WEATHER_VAR_DAILY_APPARENT_TEMPERATURE_MIN      = "apparent_temperature_min"
	WEATHER_VAR_DAILY_SUNRISE                       = "sunrise"
	WEATHER_VAR_DAILY_SUNSET                        = "sunset"
	WEATHER_VAR_DAILY_UV_INDEX_MAX                  = "uv_index_max"
	WEATHER_VAR_DAILY_UV_INDEX_CLEAR_SKY_MAX        = "uv_index_clear_sky_max"
	WEATHER_VAR_DAILY_PRECIPITATION_SUM             = "precipitation_sum"
	WEATHER_VAR_DAILY_RAIN_SUM                      = "rain_sum"
	WEATHER_VAR_DAILY_SHOWERS_SUM                   = "showers_sum"
	WEATHER_VAR_DAILY_SNOWFALL_SUM                  = "snowfall_sum"
	WEATHER_VAR_DAILY_PRECIPITATION_HOURS           = "precipitation_hours"
	WEATHER_VAR_DAILY_PRECIPITATION_PROBABILITY_MAX = "precipitation_probability_max"
	WEATHER_VAR_DAILY_WINDSPEED_10M_MAX             = "windspeed_10m_max"
	WEATHER_VAR_DAILY_WINDGUSTS_10M_MAX             = "windgusts_10m_max"
	WEATHER_VAR_DAILY_WINDDIRECTION_10M_DOMINANT    = "winddirection_10m_dominant"
	WEATHER_VAR_DAILY_SHORTWAVE_RADIATION_SUM       = "shortwave_radiation_sum"
	WEATHER_VAR_DAILY_ET0_FAO_EVAPOTRANSPIRATION    = "et0_fao_evapotranspiration"

	WEATHER_VAR_MINUTELY_15_TEMPERATURE_2M           = "temperature_2m"
	WEATHER_VAR_MINUTELY_15_RELATIVEHUMIDITY_2M      = "relativehumidity_2m"
	WEATHER_VAR_MINUTELY_15_DEWPOINT_2M              = "dewpoint_2m	Instant"
	WEATHER_VAR_MINUTELY_15_APPARENT_TEMPERATURE     = "apparent_temperature"
	WEATHER_VAR_MINUTELY_15_SHORTWAVE_RADIATION      = "shortwave_radiation"
	WEATHER_VAR_MINUTELY_15_DIRECT_RADIATION         = "direct_radiation"
	WEATHER_VAR_MINUTELY_15_DIRECT_NORMAL_IRRADIANCE = "direct_normal_irradiance"
	WEATHER_VAR_MINUTELY_15_DIFFUSE_RADIATION        = "diffuse_radiation"
	WEATHER_VAR_MINUTELY_15_LIGHTNING_POTENTIAL      = "lightning_potential"
	WEATHER_VAR_MINUTELY_15_PRECIPITATION            = "precipitation"
	WEATHER_VAR_MINUTELY_15_SNOWFALL                 = "snowfall"
	WEATHER_VAR_MINUTELY_15_RAIN                     = "rain"
	WEATHER_VAR_MINUTELY_15_SHOWERS                  = "showers"
	WEATHER_VAR_MINUTELY_15_SNOWFALL_HEIGHT          = "snowfall_height"
	WEATHER_VAR_MINUTELY_15_FREEZINGLEVEL_HEIGHT     = "freezinglevel_height"
	WEATHER_VAR_MINUTELY_15_CAPE                     = "cape"
	WEATHER_VAR_MINUTELY_15_WINDSPEED_10M            = "windspeed_10m"
	WEATHER_VAR_MINUTELY_15_WINDSPEED_80M            = "windspeed_80m"
	WEATHER_VAR_MINUTELY_15_WINDDIRECTION_10M        = "winddirection_10m"
	WEATHER_VAR_MINUTELY_15_WINDDIRECTION_80M        = "winddirection_80m"
	WEATHER_VAR_MINUTELY_15_WINDGUSTS_10M            = "windgusts_10m"
	WEATHER_VAR_MINUTELY_15_VISIBILITY               = "visibility"
	WEATHER_VAR_MINUTELY_15_WEATHERCODE              = "weathercode"

	WEATHER_VAR_HOURLY_TEMPERATURE_2M             = "temperature_2m"
	WEATHER_VAR_HOURLY_RELATIVEHUMIDITY_2M        = "relativehumidity_2m"
	WEATHER_VAR_HOURLY_DEWPOINT_2M                = "dewpoint_2m"
	WEATHER_VAR_HOURLY_APPARENT_TEMPERATURE       = "apparent_temperature"
	WEATHER_VAR_HOURLY_PRECIPITATION_PROBABILITY  = "precipitation_probability"
	WEATHER_VAR_HOURLY_PRECIPITATION              = "precipitation"
	WEATHER_VAR_HOURLY_RAIN                       = "rain"
	WEATHER_VAR_HOURLY_SHOWERS                    = "showers"
	WEATHER_VAR_HOURLY_SNOWFALL                   = "snowfall"
	WEATHER_VAR_HOURLY_SNOW_DEPTH                 = "snow_depth"
	WEATHER_VAR_HOURLY_WEATHERCODE                = "weathercode"
	WEATHER_VAR_HOURLY_PRESSURE_MSL               = "pressure_msl"
	WEATHER_VAR_HOURLY_SURFACE_PRESSURE           = "surface_pressure"
	WEATHER_VAR_HOURLY_CLOUDCOVER                 = "cloudcover"
	WEATHER_VAR_HOURLY_CLOUDCOVER_LOW             = "cloudcover_low"
	WEATHER_VAR_HOURLY_CLOUDCOVER_MID             = "cloudcover_mid"
	WEATHER_VAR_HOURLY_CLOUDCOVER_HIGH            = "cloudcover_high"
	WEATHER_VAR_HOURLY_VISIBILITY                 = "visibility"
	WEATHER_VAR_HOURLY_EVAPOTRANSPIRATION         = "evapotranspiration"
	WEATHER_VAR_HOURLY_ET0_FAO_EVAPOTRANSPIRATION = "et0_fao_evapotranspiration"
	WEATHER_VAR_HOURLY_VAPOR_PRESSURE_DEFICIT     = "vapor_pressure_deficit"
	WEATHER_VAR_HOURLY_WINDSPEED_10M              = "windspeed_10m"
	WEATHER_VAR_HOURLY_WINDSPEED_80M              = "windspeed_80m"
	WEATHER_VAR_HOURLY_WINDSPEED_120M             = "windspeed_120m"
	WEATHER_VAR_HOURLY_WINDSPEED_180M             = "windspeed_180m"
	WEATHER_VAR_HOURLY_WINDDIRECTION_10M          = "winddirection_10m"
	WEATHER_VAR_HOURLY_WINDDIRECTION_80M          = "winddirection_80m"
	WEATHER_VAR_HOURLY_WINDDIRECTION_120M         = "winddirection_120m"
	WEATHER_VAR_HOURLY_WINDDIRECTION_180M         = "winddirection_180m"
	WEATHER_VAR_HOURLY_WINDGUSTS_10M              = "windgusts_10m"
	WEATHER_VAR_HOURLY_TEMPERATURE_80M            = "temperature_80m"
	WEATHER_VAR_HOURLY_TEMPERATURE_120M           = "temperature_120m"
	WEATHER_VAR_HOURLY_TEMPERATURE_180M           = "temperature_180m"
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_0CM       = "soil_temperature_0cm"
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_6CM       = "soil_temperature_6cm"
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_18CM      = "soil_temperature_18cm"
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_54CM      = "soil_temperature_54cm"
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_0_TO_1CM     = "soil_moisture_0_to_1cm"
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_1_TO_3CM     = "soil_moisture_1_to_3cm"
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_3_TO_9CM     = "soil_moisture_3_to_9cm"
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_9_TO_27CM    = "soil_moisture_9_to_27cm"
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_27_TO_81CM   = "soil_moisture_27_to_81cm"

	WEATHER_VAR_CURRENT_TEMPERATURE_2M       = "temperature_2m"
	WEATHER_VAR_CURRENT_RELATIVEHUMIDITY_2M  = "relativehumidity_2m"
	WEATHER_VAR_CURRENT_APPARENT_TEMPERATURE = "apparent_temperature"
	WEATHER_VAR_CURRENT_IS_DAY               = "is_day"
	WEATHER_VAR_CURRENT_PRECIPITATION        = "precipitation"
	WEATHER_VAR_CURRENT_RAIN                 = "rain"
	WEATHER_VAR_CURRENT_SHOWERS              = "showers"
	WEATHER_VAR_CURRENT_SNOWFALL             = "snowfall"
	WEATHER_VAR_CURRENT_WEATHERCODE          = "weathercode"
	WEATHER_VAR_CURRENT_CLOUDCOVER           = "cloudcover"
	WEATHER_VAR_CURRENT_PRESSURE_MSL         = "pressure_msl"
	WEATHER_VAR_CURRENT_SURFACE_PRESSURE     = "surface_pressure"
	WEATHER_VAR_CURRENT_WINDSPEED_10M        = "windspeed_10m"
	WEATHER_VAR_CURRENT_WINDDIRECTION_10M    = "winddirection_10m"
	WEATHER_VAR_CURRENT_WINDGUSTS_10M        = "windgusts_10m&hourly=temperature_2m"

	WEATHER_PARAMETER_LATITUDE           = "latitude"
	WEATHER_PARAMETER_LONGITUDE          = "longitude"
	WEATHER_PARAMETER_ELEVATION          = "elevation"
	WEATHER_PARAMETER_MINUTELY_15        = "minutely_15"
	WEATHER_PARAMETER_HOURLY             = "hourly"
	WEATHER_PARAMETER_DAILY              = "daily"
	WEATHER_PARAMETER_CURRENT            = "current"
	WEATHER_PARAMETER_TEMPERATURE_UNIT   = "temperature_unit"
	WEATHER_PARAMETER_WINDSPEED_UNIT     = "windspeed_unit"
	WEATHER_PARAMETER_PRECIPITATION_UNIT = "precipitation_unit"
	WEATHER_PARAMETER_TIMEFORMAT         = "timeformat"
	WEATHER_PARAMETER_TIMEZONE           = "timezone"
	WEATHER_PARAMETER_PAST_DAYS          = "past_days"
	WEATHER_PARAMETER_FORECAST_DAYS      = "forecast_days"
	WEATHER_PARAMETER_START_DATE         = "start_date"
	WEATHER_PARAMETER_END_DATE           = "end_date"
	WEATHER_PARAMETER_MODELS             = "models"
	WEATHER_PARAMETER_CELL_SELECTION     = "cell_selection"
	WEATHER_PARAMETER_APIKEY             = "apikey"

	WEATHER_WINDSPEED_UNIT_MS  = "ms"
	WEATHER_WINDSPEED_UNIT_MPH = "mph"
	WEATHER_WINDSPEED_UNIT_KN  = "kn"

	WEATHER_PRECIPIATION_UNIT_MM   = "mm"
	WEATHER_PRECIPIATION_UNIT_INCH = "inch"

	WEATHER_TEMPERATURE_UNIT_CELSIUS    = "celsius"
	WEATHER_TEMPERATURE_UNIT_FAHRENHEIT = "fahrenheit"
)

var WEATHER_VALID_DAILY_VARS []string = []string{
	WEATHER_VAR_DAILY_WEATHERCODE,
	WEATHER_VAR_DAILY_TEMPERATURE_2M_MAX,
	WEATHER_VAR_DAILY_TEMPERATURE_2M_MIN,
	WEATHER_VAR_DAILY_APPARENT_TEMPERATURE_MAX,
	WEATHER_VAR_DAILY_APPARENT_TEMPERATURE_MIN,
	WEATHER_VAR_DAILY_SUNRISE,
	WEATHER_VAR_DAILY_SUNSET,
	WEATHER_VAR_DAILY_UV_INDEX_MAX,
	WEATHER_VAR_DAILY_UV_INDEX_CLEAR_SKY_MAX,
	WEATHER_VAR_DAILY_PRECIPITATION_SUM,
	WEATHER_VAR_DAILY_RAIN_SUM,
	WEATHER_VAR_DAILY_SHOWERS_SUM,
	WEATHER_VAR_DAILY_SNOWFALL_SUM,
	WEATHER_VAR_DAILY_PRECIPITATION_HOURS,
	WEATHER_VAR_DAILY_PRECIPITATION_PROBABILITY_MAX,
	WEATHER_VAR_DAILY_WINDSPEED_10M_MAX,
	WEATHER_VAR_DAILY_WINDGUSTS_10M_MAX,
	WEATHER_VAR_DAILY_WINDDIRECTION_10M_DOMINANT,
	WEATHER_VAR_DAILY_SHORTWAVE_RADIATION_SUM,
	WEATHER_VAR_DAILY_ET0_FAO_EVAPOTRANSPIRATION,
}

var WEATHER_VALID_HOURLY_VARS []string = []string{
	WEATHER_VAR_HOURLY_TEMPERATURE_2M,
	WEATHER_VAR_HOURLY_RELATIVEHUMIDITY_2M,
	WEATHER_VAR_HOURLY_DEWPOINT_2M,
	WEATHER_VAR_HOURLY_APPARENT_TEMPERATURE,
	WEATHER_VAR_HOURLY_PRECIPITATION_PROBABILITY,
	WEATHER_VAR_HOURLY_PRECIPITATION,
	WEATHER_VAR_HOURLY_RAIN,
	WEATHER_VAR_HOURLY_SHOWERS,
	WEATHER_VAR_HOURLY_SNOWFALL,
	WEATHER_VAR_HOURLY_SNOW_DEPTH,
	WEATHER_VAR_HOURLY_WEATHERCODE,
	WEATHER_VAR_HOURLY_PRESSURE_MSL,
	WEATHER_VAR_HOURLY_SURFACE_PRESSURE,
	WEATHER_VAR_HOURLY_CLOUDCOVER,
	WEATHER_VAR_HOURLY_CLOUDCOVER_LOW,
	WEATHER_VAR_HOURLY_CLOUDCOVER_MID,
	WEATHER_VAR_HOURLY_CLOUDCOVER_HIGH,
	WEATHER_VAR_HOURLY_VISIBILITY,
	WEATHER_VAR_HOURLY_EVAPOTRANSPIRATION,
	WEATHER_VAR_HOURLY_ET0_FAO_EVAPOTRANSPIRATION,
	WEATHER_VAR_HOURLY_VAPOR_PRESSURE_DEFICIT,
	WEATHER_VAR_HOURLY_WINDSPEED_10M,
	WEATHER_VAR_HOURLY_WINDSPEED_80M,
	WEATHER_VAR_HOURLY_WINDSPEED_120M,
	WEATHER_VAR_HOURLY_WINDSPEED_180M,
	WEATHER_VAR_HOURLY_WINDDIRECTION_10M,
	WEATHER_VAR_HOURLY_WINDDIRECTION_80M,
	WEATHER_VAR_HOURLY_WINDDIRECTION_120M,
	WEATHER_VAR_HOURLY_WINDDIRECTION_180M,
	WEATHER_VAR_HOURLY_WINDGUSTS_10M,
	WEATHER_VAR_HOURLY_TEMPERATURE_80M,
	WEATHER_VAR_HOURLY_TEMPERATURE_120M,
	WEATHER_VAR_HOURLY_TEMPERATURE_180M,
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_0CM,
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_6CM,
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_18CM,
	WEATHER_VAR_HOURLY_SOIL_TEMPERATURE_54CM,
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_0_TO_1CM,
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_1_TO_3CM,
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_3_TO_9CM,
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_9_TO_27CM,
	WEATHER_VAR_HOURLY_SOIL_MOISTURE_27_TO_81CM,
}

var WEATHER_VALID_CURRENT_VARS []string = []string{
	WEATHER_VAR_CURRENT_TEMPERATURE_2M,
	WEATHER_VAR_CURRENT_RELATIVEHUMIDITY_2M,
	WEATHER_VAR_CURRENT_APPARENT_TEMPERATURE,
	WEATHER_VAR_CURRENT_IS_DAY,
	WEATHER_VAR_CURRENT_PRECIPITATION,
	WEATHER_VAR_CURRENT_RAIN,
	WEATHER_VAR_CURRENT_SHOWERS,
	WEATHER_VAR_CURRENT_SNOWFALL,
	WEATHER_VAR_CURRENT_WEATHERCODE,
	WEATHER_VAR_CURRENT_CLOUDCOVER,
	WEATHER_VAR_CURRENT_PRESSURE_MSL,
	WEATHER_VAR_CURRENT_SURFACE_PRESSURE,
	WEATHER_VAR_CURRENT_WINDSPEED_10M,
	WEATHER_VAR_CURRENT_WINDDIRECTION_10M,
	WEATHER_VAR_CURRENT_WINDGUSTS_10M,
}

var WEATHER_VALID_MINUTELY_15_VARS []string = []string{
	WEATHER_VAR_MINUTELY_15_TEMPERATURE_2M,
	WEATHER_VAR_MINUTELY_15_RELATIVEHUMIDITY_2M,
	WEATHER_VAR_MINUTELY_15_DEWPOINT_2M,
	WEATHER_VAR_MINUTELY_15_APPARENT_TEMPERATURE,
	WEATHER_VAR_MINUTELY_15_SHORTWAVE_RADIATION,
	WEATHER_VAR_MINUTELY_15_DIRECT_RADIATION,
	WEATHER_VAR_MINUTELY_15_DIRECT_NORMAL_IRRADIANCE,
	WEATHER_VAR_MINUTELY_15_DIFFUSE_RADIATION,
	WEATHER_VAR_MINUTELY_15_LIGHTNING_POTENTIAL,
	WEATHER_VAR_MINUTELY_15_PRECIPITATION,
	WEATHER_VAR_MINUTELY_15_SNOWFALL,
	WEATHER_VAR_MINUTELY_15_RAIN,
	WEATHER_VAR_MINUTELY_15_SHOWERS,
	WEATHER_VAR_MINUTELY_15_SNOWFALL_HEIGHT,
	WEATHER_VAR_MINUTELY_15_FREEZINGLEVEL_HEIGHT,
	WEATHER_VAR_MINUTELY_15_CAPE,
	WEATHER_VAR_MINUTELY_15_WINDSPEED_10M,
	WEATHER_VAR_MINUTELY_15_WINDSPEED_80M,
	WEATHER_VAR_MINUTELY_15_WINDDIRECTION_10M,
	WEATHER_VAR_MINUTELY_15_WINDDIRECTION_80M,
	WEATHER_VAR_MINUTELY_15_WINDGUSTS_10M,
	WEATHER_VAR_MINUTELY_15_VISIBILITY,
	WEATHER_VAR_MINUTELY_15_WEATHERCODE,
}

var WEATHER_CODE_TO_STRING_MAP map[int]string = map[int]string{
	0:  "Clear sky",
	1:  "Mainly clear",
	2:  "partly cloudy",
	3:  "overcast",
	45: "fog",
	48: "depositing rime fog",
	51: "light drizzle",
	53: "moderate drizzle",
	55: "dense drizzle",
	56: "light freezing drizzle",
	57: "dense freezing drizzle",
	61: "slight rain",
	63: "medium rain",
	65: "heavy rain",
	66: "light freezing rain",
	67: "heavy freezing rain",
	71: "slight snow fall",
	73: "medium snow fall",
	75: "heavy snow fall",
	77: "snow grains",
	81: "slight rain showers",
	82: "moderate rain showers",
	83: "violent rain showers",
	85: "slight snow showers",
	86: "heavy snow showers",
	95: "slight or moderate thunderstorm",
	96: "thunderstorm with slight hail",
	99: "thunderstorm with heavy hail",
}
